### ISSUE TITLE
Build issue: static TTFs aren’t building from AFDKO

### ISSUE THREAD

**Issue by arrowtype** [thundernixon/recursive#486]
I’ve made some useful updates for build 1.080 in the [pnum](https://github.com/arrowtype/recursive/tree/e687ca702da4ce390e7ca92f3bbc8bb6682d942c) branch, but I am blocked from building TTFs on a build error. Static OTFs are building and autohinting, however.

Here’s the error:

```
(venv) 
type-repos/recursive/mastering  pnum ✗                                                                                                                                                         1h19m ⚑ ◒  ⍉
▶ py build_static.py build/static ../fonts_1.080 --ttf
🏗  Copying files
🏗  Making TTF sources
   |██████████████████████████████████████████████████| 100.0% Complete
🏗  Initial TTF building
   |██████████████████████████████████████████████████| 100.0% Complete
🏗  TTF table fixing
Traceback (most recent call last):
  File "build_static.py", line 791, in <module>
    build_static(cff_root, ttf_root, args.out, otf=args.otf, ttf=args.ttf)
  File "build_static.py", line 770, in build_static
    makeSFNT(ttf_root, d, kind="ttf")
  File "build_static.py", line 702, in makeSFNT
    printProgressBar(0, len(files), prefix='  ', suffix='Complete', length=50)
  File "/Users/stephennixon/type-repos/recursive/mastering/utils.py", line 60, in printProgressBar
    percent = ("{0:."+str(decimals)+"f}").format(100*(iteration/float(total)))
ZeroDivisionError: float division by zero
```

But, that `ZeroDivisionError: float division by zero` just comes from a progress bar trying to be made by checking completion of processing files in a folder with no TTF files. So, division by zero. The real issue is that those TTFs aren’t building, so they can’t be processed. This is probably happening in the `buildSFNT` function, possibly due to issues in AFDKO.

https://github.com/arrowtype/recursive/blob/e687ca702da4ce390e7ca92f3bbc8bb6682d942c/mastering/build_static.py#L651-L661

(etc)

Though, it might also be a silly error, such as the build system expecting to build all fonts at once... I think I’ve run into this before, but I forget how I fixed it then. So, I’m making an issue that I can search and find if this happens again. I’ll update this when I figure out the fix!

**Comment by arrowtype** [comment]
The above didn't fix the build, but I’m still glad I made those suffixes follow the norm.

I have found that the new `beta` character lacks a Unicode value (should be `03B2`) in the Sans sources. This could very well be the problem.
